services:
  db:
    container_name: mysql
    image: mysql:8.0.33
    ports:
      - ${LOCAL_DB_PORT}:3306
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    env_file:
      - ./.env
    restart: always

  database-adminer:
    container_name: database-adminer
    image: adminer:latest
    ports:
      - ${LOCAL_DB_ADMINER_HOST}:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DESIGN=hydra
      - ADMINER_PLUGINS=tables-filter tinymce

  redis:
    container_name: redis
    image: redis:alpine
    hostname: ${LOCAL_REDIS_HOST_NAME}
    ports:
      - ${LOCAL_REDIS_PORT}:6379
    labels:
      - "name=redis"
      - "mode=standalone"
    extra_hosts:
      - host.docker.internal:host-gateway
    command: redis-server --port 6379
    restart: always
